version: 2
jobs:
  build:
    working_directory: ~/ci
    docker:
      - image: debian:10

    steps:
      # basic dependencies required by circleci:
      - run: apt-get update -qq && apt-get install -qqy git unzip ssh ca-certificates tar gzip
      - checkout

      - run:
          name: Installing dotnet
          command: bash ./.circleci/install.sh

      - run:
          name: Building and testing
          command: bash ./.circleci/build-and-test.sh

  deploy:
    working_directory: ~/ci
    docker:
      - image: debian:10

    steps:
      - run: apt-get update -qq && apt-get install -qqy git unzip ssh ca-certificates tar gzip
      - checkout
      - run:
          name: Installing dotnet
          command: bash ./.circleci/install.sh
          
      - run:
          name: Nuget Publish
          command: bash ./.circleci/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
